name: "Create Dart Release"
description: "An action to create a github release from a dart package"
author: "Skycoder42"
inputs:
  src-dir:
    description: "The local package directory"
    required: true
outputs:
  update:
    description: "Is true/false, depending on wheter a new release is required or not"
  newVersion:
    description: "If a new release is required, it holds the sanitized version"
  title:
    description: "If a new release is required, it holds the recommended release title"
  bodyPath:
    description: "If a new release is required, it holds the path to a file that contains the part of the changelog that matters for the new version."
runs:
  using: "node12"
  main: "dist/main.js"
