name: Continous Integration

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - uses: actions/checkout@v3
      - run: rm -rf node_modules dist
        shell: bash
      - name: cache node_modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: node_modules-${{runner.os}}-${{hashFiles('yarn.lock')}}
      - run: yarn
      - run: yarn build
      - run: yarn test
